### ISSUE TITLE
can make a online dema on huggingface space

### ISSUE THREAD

**Issue by sunenlu7484** [berkegokmen1/dual-enc-3d-gan-inversion#2]
Can make a online dema on huggingface space. it is hardly to run with this code

**Comment by berkegokmen1** [comment]
working on it.

**Comment by sunenlu7484** [comment]
i do not find it on huggingface space .  can share your demo url for us. i am going to try it _

**Comment by berkegokmen1** [comment]
Hi, it's because it's under development. It'll be available when the code for hf is ready. Thanks.
